name: creditscore
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+3
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image:
  data_connection_checker: ^0.3.4
  dio:
  pdf: ^3.4.2
  open_file:
  syncfusion_flutter_gauges:
  syncfusion_flutter_pdfviewer:
  font_awesome_flutter: ^8.10.0
  google_fonts: ^1.1.1
  flutter_xlider: ^3.4.0
  percent_indicator:
  provider:
  file_picker:
  flutter_hooks:
  image_picker: ^0.6.6+5
  flutter_staggered_animations: ^0.1.3
  simple_animations: ^1.3.3
  permission_handler: ^5.0.1+1
  shared_preferences: ^0.5.4+5
  bottom_navy_bar:
  fluttertoast:
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  country_code_picker:
  progress_dialog:
  path_provider:
  http:
  flutter_downloader: ^1.6.0
  image_gallery_saver: ^1.6.9
  jwt_decoder: ^2.0.1
  http_parser:
  intl:
  platform:
  shimmer:
  geolocator:
  geocoder:
  flutter_screenutil: ^5.0.0+2
  url_launcher:





dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Multi
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
